### Get all products with default pagination
GET http://localhost:5072/api/products

### Get products with pagination
GET http://localhost:5072/api/products?page=2&pageSize=1

### Get products filtered by SKU
GET http://localhost:5072/api/products?sku=123

### Get products filtered by name
GET http://localhost:5072/api/products?name=pony

### Get products filtered by price
GET http://localhost:5072/api/products?price=15.99

### Get products sorted by price in ascending order
GET http://localhost:5072/api/products?sortBy=price&sortDirection=asc

### Get products sorted by price in descending order
GET http://localhost:5072/api/products?sortBy=price&sortDirection=desc

### Combine filtering, sorting, and pagination
GET http://localhost:5072/api/products?page=1&pageSize=10&sortBy=name&sortDirection=asc&name=pony
